import React from 'react'
import About from '../../../components/About'
export const metadata = {
    title: "About",
  
    description: "Generated by create next app",
  };
const Aboutroute = () => {
  return (
    <About />
  )
}

export default Aboutroute