import React from 'react'
import Services from '../../components/Services'
export const metadata = {
    title: "Services",
  
    description: "Generated by create next app",
  };
const Servicesroute = () => {
  return (
    <Services />
  )
}

export default Servicesroute