import React from 'react'
import Home from '../../components/Home'

export const metadata = {
  title: "Home",

  description: "Generated by create next app",
};
const Homeroute = () => {
  return (
    <Home />
  )
}

export default Homeroute